-- Restore missing extended nutrition for local basic foods already saved.
-- Values per 100 g/ml are the same as src/data/basicFoodExtendedNutrition.ts.
-- Match only basic-food records by stable key, or by exact name for old rows
-- without a key. Keep existing pantry and standalone ingredient values;
-- linked ingredients follow their pantry or saved-dish source.
create temp table basic_food_extended_backfill (
  id text primary key,
  name text unique not null,
  fiber float not null,
  sugars float not null,
  salt float not null
);
insert into basic_food_extended_backfill (id, name, fiber, sugars, salt) values
  ('riso-bianco', 'Riso bianco', 1, 0.2, 0),
  ('riso-basmati', 'Riso basmati', 1.3, 0.1, 0.01),
  ('riso-integrale', 'Riso integrale', 5, 0.6, 0),
  ('pasta-semola', 'Pasta di semola', 5.1, 0.4, 0),
  ('pasta-integrale', 'Pasta integrale', 11.5, 0.7, 0),
  ('pasta-uovo', 'Pasta all''uovo', 3.4, 3.7, 0),
  ('pane-bianco', 'Pane bianco', 2.5, 0.2, 1.7),
  ('pane-integrale', 'Pane integrale', 7, 0.7, 1.4),
  ('avena-fiocchi', 'Avena in fiocchi', 10.5, 1, 0),
  ('quinoa', 'Quinoa', 8.3, 3.1, 0),
  ('farro', 'Farro', 10.7, 6.8, 0.02),
  ('orzo-perlato', 'Orzo perlato', 13.4, 1.4, 0),
  ('couscous', 'Couscous', 5, 0.4, 0.03),
  ('grissini', 'Grissini', 3.2, 1.4, 2),
  ('fette-biscottate', 'Fette biscottate', 2.9, 14.2, 1.3),
  ('cracker', 'Cracker', 2.1, 0, 1.5),
  ('farina-00', 'Farina 00', 4.3, 0.6, 0),
  ('patate-fritte', 'Patate fritte', 3.8, 0.3, 0.5),
  ('ceci-secchi', 'Ceci secchi', 21, 2.4, 0),
  ('fagioli-borlotti-secchi', 'Fagioli borlotti secchi', 22.6, 1.2, 0),
  ('fagioli-cannellini-secchi', 'Fagioli cannellini secchi', 22.6, 1.2, 0),
  ('lenticchie-secche', 'Lenticchie secche', 23.2, 1.3, 0),
  ('piselli', 'Piselli', 5.3, 2.3, 0),
  ('fave', 'Fave', 5.4, 5.7, 0.05),
  ('hummus', 'Hummus', 6.2, 0.8, 1.1),
  ('tofu', 'Tofu', 0.5, 0.6, 0.1),
  ('seitan', 'Seitan', 0.6, 0, 0.07),
  ('edamame', 'Edamame', 5.5, 1.4, 0),
  ('lupini-secchi', 'Lupini secchi', 18.9, 2.8, 0.04),
  ('fagioli-neri-secchi', 'Fagioli neri secchi', 15.5, 2.1, 0.01),
  ('fagioli-rossi-secchi', 'Fagioli rossi secchi', 24.9, 2.1, 0.06),
  ('fagioli-azuki-secchi', 'Fagioli azuki secchi', 12.7, 0, 0.01),
  ('fagioli-mung-secchi', 'Fagioli mung secchi', 16.3, 6.6, 0.04),
  ('soia-gialla-secca', 'Soia gialla secca', 22, 6.8, 0),
  ('lenticchie-rosse-secche', 'Lenticchie rosse secche', 18.2, 1.8, 0),
  ('zucchine', 'Zucchine', 1.1, 1.8, 0),
  ('melanzane', 'Melanzane', 2.7, 2.4, 0),
  ('pomodori', 'Pomodori', 1.2, 3.2, 0),
  ('insalata-lattuga', 'Insalata / lattuga', 1.3, 1.5, 0),
  ('spinaci', 'Spinaci', 1.9, 0.1, 0.2),
  ('broccoli', 'Broccoli', 3.2, 1.9, 0),
  ('carote', 'Carote', 2.7, 6, 0.1),
  ('patate', 'Patate', 2.1, 0.7, 0),
  ('peperoni', 'Peperoni', 1.7, 5.2, 0),
  ('cipolla', 'Cipolla', 1.9, 4.8, 0),
  ('funghi-champignon', 'Funghi champignon', 1.9, 0.3, 0),
  ('zucca', 'Zucca', 2.2, 3.9, 0),
  ('cavolfiore', 'Cavolfiore', 2, 1.7, 0),
  ('finocchi', 'Finocchi', 2.6, 2.2, 0.1),
  ('rucola', 'Rucola', 1.7, 0, 0.1),
  ('cetrioli', 'Cetrioli', 0.8, 1.8, 0),
  ('asparagi', 'Asparagi', 1.8, 1.9, 0),
  ('cavolo-cappuccio', 'Cavolo cappuccio', 3.5, 4.2, 0),
  ('cavolo-rosso', 'Cavolo rosso', 2.6, 3.9, 0),
  ('cavolo-verza', 'Cavolo verza', 3.1, 2.8, 0),
  ('cavolo-nero', 'Cavolo nero', 4.2, 2.5, 0.3),
  ('cavolini-bruxelles', 'Cavolini di Bruxelles', 4, 2.8, 0),
  ('cavolo-rapa', 'Cavolo rapa', 1.4, 3.6, 0),
  ('broccolo-romanesco', 'Broccolo romanesco', 3.2, 1.9, 0),
  ('bietole', 'Bietole', 1.6, 1.5, 0.2),
  ('cicoria', 'Cicoria', 3, 1.6, 0),
  ('radicchio', 'Radicchio', 3, 1.6, 0),
  ('indivia', 'Indivia', 1.2, 2.4, 0),
  ('scarola', 'Scarola', 1.2, 1.2, 0.1),
  ('valeriana', 'Valeriana', 1.5, 0, 0.01),
  ('sedano', 'Sedano', 2.2, 1.3, 0.2),
  ('porro', 'Porro', 3.2, 3.7, 0),
  ('cipollotto', 'Cipollotto', 2.6, 2.3, 0.04),
  ('carciofi', 'Carciofi', 5.4, 1, 0.24),
  ('fagiolini', 'Fagiolini', 3, 3.3, 0),
  ('barbabietola', 'Barbabietola rossa', 2.3, 8.4, 0.1),
  ('rapa-bianca', 'Rapa bianca', 1.8, 3.8, 0.1),
  ('cime-rapa', 'Cime di rapa', 2.7, 0.4, 0.08),
  ('ravanelli', 'Ravanelli', 1.6, 1.9, 0.1),
  ('patata-dolce', 'Patata dolce', 3, 4.2, 0.1),
  ('topinambur', 'Topinambur', 12.1, 4, 0),
  ('pastinaca', 'Pastinaca', 2.1, 3.1, 0),
  ('agretti', 'Agretti', 2.2, 1.3, 0.1),
  ('cardi', 'Cardi', 1.6, 0.5, 0.1),
  ('puntarelle', 'Puntarelle', 3, 1.6, 0),
  ('taccole', 'Taccole', 2.6, 4, 0.01),
  ('mais-dolce', 'Mais dolce', 3, 5.1, 0),
  ('germogli-soia', 'Germogli di soia', 2.4, 4.6, 0.1),
  ('daikon', 'Daikon', 1.6, 2.5, 0.05),
  ('okra', 'Okra', 3.2, 1.5, 0.02),
  ('pak-choi', 'Pak choi', 1.1, 1.2, 0),
  ('fiori-zucca', 'Fiori di zucca', 1.2, 0.6, 0.01),
  ('funghi-porcini', 'Funghi porcini', 6, 0.1, 0),
  ('funghi-shiitake', 'Funghi shiitake', 2.5, 2.4, 0.02),
  ('mela', 'Mela', 1.4, 11.5, 0),
  ('banana', 'Banana', 2.7, 15.6, 0),
  ('arancia', 'Arancia', 2.7, 7.6, 0),
  ('pera', 'Pera', 2.9, 9, 0),
  ('fragole', 'Fragole', 3.8, 5.6, 0),
  ('uva', 'Uva', 1.5, 14.6, 0),
  ('kiwi', 'Kiwi', 2.4, 8.9, 0),
  ('anguria', 'Anguria', 0.5, 7.9, 0),
  ('melone', 'Melone', 0.9, 7.9, 0.1),
  ('pesca', 'Pesca', 1.9, 8, 0),
  ('ananas', 'Ananas', 1.2, 10.5, 0),
  ('mandarino', 'Mandarino', 1.7, 8.6, 0),
  ('avocado', 'Avocado', 5.5, 1.1, 0),
  ('limone', 'Limone', 2, 2.5, 0),
  ('albicocche', 'Albicocche', 1.7, 6.7, 0),
  ('ciliegie', 'Ciliegie', 2.1, 12.8, 0),
  ('susine', 'Susine', 1.6, 8.8, 0),
  ('nettarine', 'Nettarine', 1.3, 8.8, 0),
  ('cachi', 'Cachi', 3.4, 13.9, 0),
  ('fichi', 'Fichi', 4.1, 12.2, 0),
  ('melograno', 'Melograno', 2.3, 13.3, 0),
  ('pompelmo', 'Pompelmo', 0.9, 6.6, 0),
  ('lime', 'Lime', 2.8, 1.7, 0.01),
  ('clementine', 'Clementine', 1.7, 8.6, 0),
  ('mirtilli', 'Mirtilli', 1.5, 10, 0),
  ('mirtilli-rossi', 'Mirtilli rossi', 2.9, 6.1, 0),
  ('lamponi', 'Lamponi', 4.3, 5.4, 0),
  ('more', 'More', 5.2, 6.1, 0),
  ('ribes-rosso', 'Ribes rosso', 4.6, 6.6, 0),
  ('frutti-bosco', 'Frutti di bosco (misti)', 4, 7, 0),
  ('mango', 'Mango', 1.6, 12.9, 0),
  ('papaya', 'Papaya', 1.8, 9.5, 0),
  ('cocco-fresco', 'Cocco fresco', 9, 4.8, 0.1),
  ('frutto-passione', 'Frutto della passione', 6.8, 8.5, 0),
  ('guava', 'Guava', 5.4, 8.9, 0.01),
  ('litchi', 'Litchi', 2, 15.7, 0),
  ('fichi-india', 'Fichi d''India', 3.6, 7.4, 0.01),
  ('nespole', 'Nespole', 1.7, 7.3, 0),
  ('datteri', 'Datteri', 7.5, 64.7, 0),
  ('prugne-secche', 'Prugne secche', 5.1, 38.1, 0),
  ('fichi-secchi', 'Fichi secchi', 10, 55.9, 0.3),
  ('uva-passa', 'Uva passa', 4.2, 70.3, 0.1),
  ('petto-pollo', 'Petto di pollo', 0, 0, 0.1),
  ('coscia-pollo', 'Coscia di pollo senza pelle', 0, 0, 0.2),
  ('pollo-intero', 'Pollo intero con pelle', 0, 0, 0.2),
  ('petto-tacchino', 'Petto di tacchino', 0, 0, 0.2),
  ('coscia-tacchino', 'Coscia di tacchino senza pelle', 0, 0, 0.2),
  ('manzo-magro', 'Manzo magro', 0, 0, 0.1),
  ('manzo-macinato-magro', 'Manzo macinato magro', 0, 0, 0.2),
  ('manzo-entrecote', 'Manzo, entrecôte', 0, 0, 0.1),
  ('vitello', 'Vitello magro', 0, 0, 0.2),
  ('maiale-lonza', 'Maiale, lonza', 0, 0, 0.1),
  ('maiale-filetto', 'Maiale, filetto', 0, 0, 0.3),
  ('maiale-costoletta', 'Maiale, costoletta', 0, 0, 0.1),
  ('agnello-coscia', 'Agnello, coscia', 0, 0, 0.2),
  ('coniglio', 'Coniglio', 0, 0, 0.1),
  ('cavallo', 'Carne di cavallo', 0, 0, 0.1),
  ('anatra-petto', 'Petto d''anatra con pelle', 0, 0, 0.2),
  ('prosciutto-crudo', 'Prosciutto crudo', 0, 0, 4.4),
  ('prosciutto-cotto', 'Prosciutto cotto', 0, 0.7, 2.4),
  ('bresaola', 'Bresaola', 0, 0, 6.8),
  ('salmone', 'Salmone fresco', 0, 0, 0.1),
  ('tonno-fresco', 'Tonno fresco', 0, 0, 0.2),
  ('tonno-naturale', 'Tonno al naturale (sgocciolato)', 0, 0, 0.7),
  ('merluzzo', 'Merluzzo', 0, 0, 0.1),
  ('nasello', 'Nasello', 0, 0, 0.2),
  ('orata', 'Orata', 0, 0, 0.15),
  ('branzino', 'Branzino', 0, 0, 0.2),
  ('trota', 'Trota', 0, 0, 0.1),
  ('pesce-spada', 'Pesce spada', 0, 0, 0.2),
  ('sgombro', 'Sgombro', 0, 0, 0.2),
  ('sardine', 'Sardine', 0, 0, 0.3),
  ('alici', 'Alici fresche', 0, 0, 0.3),
  ('sogliola', 'Sogliola', 0, 0, 0.3),
  ('gamberi', 'Gamberi', 0, 0, 0.8),
  ('calamari', 'Calamari', 0, 0, 0.6),
  ('seppie', 'Seppie', 0, 0, 0.7),
  ('polpo', 'Polpo', 0, 0, 0.6),
  ('cozze', 'Cozze', 0, 0, 0.7),
  ('vongole', 'Vongole', 0, 0, 0.6),
  ('salmone-affumicato', 'Salmone affumicato', 0, 0, 4.1),
  ('uovo-intero', 'Uovo intero', 0, 0.3, 0.4),
  ('albume-uovo', 'Albume d''uovo', 0, 0.4, 0.5),
  ('latte-intero', 'Latte intero', 0, 4.8, 0.1),
  ('latte-parz-scremato', 'Latte parzialmente scremato', 0, 4.8, 0.1),
  ('yogurt-bianco-intero', 'Yogurt bianco intero', 0, 4.5, 0.1),
  ('yogurt-greco-0', 'Yogurt greco 0%', 0, 3.5, 0.1),
  ('yogurt-greco-intero', 'Yogurt greco intero', 0, 3.5, 0.1),
  ('mozzarella', 'Mozzarella', 0, 0.7, 0.4),
  ('mozzarella-light', 'Mozzarella light', 0, 0.7, 0.5),
  ('parmigiano', 'Parmigiano Reggiano', 0, 0, 1.6),
  ('grana-padano', 'Grana Padano', 0, 0, 1.5),
  ('ricotta', 'Ricotta', 0, 3.3, 0.1),
  ('formaggio-spalmabile', 'Formaggio spalmabile', 0, 1.4, 1.2),
  ('olio-evo', 'Olio extravergine d''oliva', 0, 0, 0),
  ('burro', 'Burro', 0, 0.1, 0),
  ('mandorle', 'Mandorle', 10.6, 6.6, 0),
  ('noci', 'Noci', 6.7, 3, 0),
  ('arachidi', 'Arachidi', 8.6, 5.9, 0),
  ('nocciole', 'Nocciole', 9.7, 3, 0),
  ('pistacchi', 'Pistacchi', 8.8, 7.2, 0),
  ('anacardi', 'Anacardi', 3.6, 3.1, 0),
  ('noci-pecan', 'Noci pecan', 9.6, 4, 0),
  ('noci-brasile', 'Noci del Brasile', 7.5, 2.3, 0),
  ('macadamia', 'Noci macadamia', 8.6, 4.6, 0),
  ('pinoli', 'Pinoli', 6.3, 4.9, 0),
  ('semi-chia', 'Semi di chia', 40.9, 1.8, 0),
  ('semi-lino', 'Semi di lino', 26.9, 1.4, 0.1),
  ('semi-zucca', 'Semi di zucca', 6, 1.4, 0),
  ('semi-girasole', 'Semi di girasole', 8, 3.4, 0),
  ('semi-sesamo', 'Semi di sesamo', 13.3, 1.2, 0),
  ('semi-canapa', 'Semi di canapa', 4, 1.5, 0.01),
  ('burro-arachidi', 'Burro d''arachidi', 6, 9, 0.4),
  ('crema-mandorle', 'Crema di mandorle 100%', 10.6, 6.6, 0),
  ('crema-nocciole', 'Crema di nocciole 100%', 9.7, 3, 0),
  ('tahina', 'Tahina', 9.3, 0.5, 0.3),
  ('passata-pomodoro', 'Passata di pomodoro', 1.5, 3.6, 0.1),
  ('polpa-pomodoro', 'Polpa di pomodoro', 1.5, 3.6, 0.1),
  ('pomodori-pelati', 'Pomodori pelati', 1.5, 3.3, 0.1),
  ('sugo-pomodoro', 'Sugo di pomodoro', 1.9, 4.1, 1.4),
  ('pesto-genovese', 'Pesto alla genovese', 2.5, 3.2, 2.7),
  ('ragu-carne', 'Ragù di carne', 0.6, 1.3, 0.8),
  ('besciamella', 'Besciamella', 0.2, 4.8, 0.7),
  ('panna-cucina', 'Panna da cucina', 0, 3.1, 0.1),
  ('maionese', 'Maionese', 0.3, 1, 1.4),
  ('ketchup', 'Ketchup', 0.9, 24.8, 2.8),
  ('senape', 'Senape', 5.3, 2.6, 4.1),
  ('salsa-soia', 'Salsa di soia', 0.8, 0.4, 14),
  ('brodo-vegetale', 'Brodo vegetale', 0, 0.2, 1),
  ('sale', 'Sale', 0, 0, 100),
  ('pepe-nero', 'Pepe nero', 25.3, 0.6, 0.05),
  ('basilico', 'Basilico', 1.6, 0.3, 0),
  ('prezzemolo', 'Prezzemolo', 4.3, 4.8, 0.1),
  ('origano', 'Origano', 42.5, 4.1, 0.06),
  ('rosmarino', 'Rosmarino', 2.9, 7.6, 0),
  ('aglio', 'Aglio', 5.8, 1.6, 0),
  ('cioccolato-fondente-70', 'Cioccolato fondente 70%', 10.9, 24, 0.03),
  ('cioccolato-latte', 'Cioccolato al latte', 1.9, 55.2, 0.5),
  ('miele', 'Miele', 0, 76, 0),
  ('zucchero', 'Zucchero', 0, 100, 0),
  ('marmellata', 'Marmellata', 2.2, 58.7, 0),
  ('gelato-crema', 'Gelato alla crema', 0, 21.9, 0.2),
  ('biscotti-secchi', 'Biscotti secchi', 2.3, 20.6, 0.5),
  ('acqua-naturale', 'Acqua naturale', 0, 0, 0),
  ('acqua-frizzante', 'Acqua frizzante', 0, 0, 0),
  ('birra-chiara', 'Birra chiara', 0, 2.2, 0),
  ('vino-rosso', 'Vino rosso', 0, 0.3, 0),
  ('vino-bianco', 'Vino bianco', 0, 0.1, 0),
  ('spritz', 'Spritz', 0, 6, 0.02),
  ('coca-cola', 'Coca Cola', 0, 10, 0),
  ('coca-cola-zero', 'Coca Cola Zero', 0, 0, 0),
  ('succo-arancia', 'Succo d''arancia', 0.3, 9.6, 0),
  ('te-freddo', 'Tè freddo', 0, 7, 0),
  ('caffe-nero', 'Caffè (nero)', 0, 0, 0);
-- The existing pantry nutrition trigger refreshes linked dish and diary rows.
update public.pantry_items p set
  food_key = coalesce(p.food_key, 'basic:' || c.id),
  fiber_100g = coalesce(p.fiber_100g, c.fiber),
  sugars_100g = coalesce(p.sugars_100g, c.sugars),
  salt_100g = coalesce(p.salt_100g, c.salt)
from basic_food_extended_backfill c
where p.source = 'basic'
  and (p.food_key = 'basic:' || c.id
    or (p.food_key is null and lower(trim(p.name)) = lower(c.name)))
  and (p.food_key is null or p.fiber_100g is null or p.sugars_100g is null or p.salt_100g is null);
-- Fill standalone saved-dish ingredients without touching user-supplied values.
update public.dish_items di set
  food_key = coalesce(di.food_key, 'basic:' || c.id),
  fiber_g = coalesce(di.fiber_g, round((c.fiber * di.quantity_g / 100)::numeric, 2)),
  sugars_g = coalesce(di.sugars_g, round((c.sugars * di.quantity_g / 100)::numeric, 2)),
  salt_g = coalesce(di.salt_g, round((c.salt * di.quantity_g / 100)::numeric, 2))
from basic_food_extended_backfill c
where di.source = 'basic' and di.pantry_item_id is null
  and (di.food_key = 'basic:' || c.id
    or (di.food_key is null and lower(trim(di.food_name)) = lower(c.name)))
  and (di.food_key is null or di.fiber_g is null or di.sugars_g is null or di.salt_g is null);
-- Fill standalone diary ingredients. Linked rows follow their saved source.
update public.meal_items mi set
  food_key = coalesce(mi.food_key, 'basic:' || c.id),
  fiber_g = coalesce(mi.fiber_g, round((c.fiber * mi.quantity_g / 100)::numeric, 2)),
  sugars_g = coalesce(mi.sugars_g, round((c.sugars * mi.quantity_g / 100)::numeric, 2)),
  salt_g = coalesce(mi.salt_g, round((c.salt * mi.quantity_g / 100)::numeric, 2))
from basic_food_extended_backfill c
where mi.source = 'basic' and mi.pantry_item_id is null and mi.dish_item_id is null
  and (mi.food_key = 'basic:' || c.id
    or (mi.food_key is null and lower(trim(mi.food_name)) = lower(c.name)))
  and (mi.food_key is null or mi.fiber_g is null or mi.sugars_g is null or mi.salt_g is null);
update public.meal_items mi set
  fiber_g = coalesce(mi.fiber_g, round((di.fiber_g * mi.quantity_g / nullif(di.quantity_g, 0))::numeric, 2)),
  sugars_g = coalesce(mi.sugars_g, round((di.sugars_g * mi.quantity_g / nullif(di.quantity_g, 0))::numeric, 2)),
  salt_g = coalesce(mi.salt_g, round((di.salt_g * mi.quantity_g / nullif(di.quantity_g, 0))::numeric, 2))
from public.dish_items di
where mi.dish_item_id = di.id and mi.pantry_item_id is null
  and di.pantry_item_id is null and di.source = 'basic'
  and (mi.fiber_g is null or mi.sugars_g is null or mi.salt_g is null);
drop table basic_food_extended_backfill;
